name: Deploy Graph Automation Infra

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: |
            .terraform
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
          restore-keys: terraform-${{ runner.os }}

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: |
          terraform plan \
            -var="resource_group_name=${{ secrets.TF_RESOURCE_GROUP_NAME }}" \
            -var="location=${{ secrets.TF_LOCATION }}" \
            -var="automation_account_name=${{ secrets.TF_AUTOMATION_ACCOUNT_NAME }}" \
            -var="runbook_name=${{ secrets.TF_RUNBOOK_NAME }}" \
            -var="script_path=./scripts/GraphUserPhotoSync-Automation.ps1" \
            -out=tfplan
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform Output
        run: terraform output -json
